### ISSUE TITLE
Do videos get placed in /data/media

### ISSUE THREAD

**Issue by davesargrad** [home-cluster/jellyfin-openshift#2]
@fabianvf 
Hi Fabian. I know this is digging a bit back (2 years). However I'm hoping that you recall where you placed videos when you got this working. I was able to use your specs for pvc, pv, deployment, and service, and get jellyfin up and running in just an hour.

Awesome!!

One slight issue I have is with configuring my first video library. In the following you'll see that i tried to get Jellyfin to find videos in /data/media and in /media... But I dont see any videos yet. 

![image](https://user-images.githubusercontent.com/48793689/113887069-2dd54080-978f-11eb-9f2c-c2e94bd2b53f.png)

You use a PVC claim that points to /data/media. I would have thought that this is the location for videos (e.g. "mp4/mpeg/avi") to get placed.. But I've placed videos there and the service doesnt seem to see them.

This is the piece of the deployment spec that refers to a /data/media volume mount

![image](https://user-images.githubusercontent.com/48793689/113885926-4002af00-978e-11eb-89a4-6c4114b04797.png)

Here you can see that my PV's and PVC's are bound
![image](https://user-images.githubusercontent.com/48793689/113886087-658fb880-978e-11eb-9112-c7215a48c127.png)

Here you can see that the jellyfin pod has access to this folder (the PV is a local-storage volume).
![image](https://user-images.githubusercontent.com/48793689/113886371-9ec82880-978e-11eb-882d-72b197414a93.png)

I created the videos folder here, since this should be the /data/media root. The pod created config, data, log, metadata, plugins, root, and transcodes

As an aside, I have successfully gotten Jellyfin to serve up video content in a non-k8s architecture. This is my first look at jellyfin in k8s.

I'm assuming that one of these PVC's point to the location where I can place videos.. Is this true?

**Comment by Didr** [comment]
Where did you point your local-storage PV to? /home/storage/jellyfin/media?
You can try entering the Jellyfin container to see if the files are available in the mountpath you specified (/data/media/):
`kubectl exec -it podID -- /bin/sh` 

Then browse around and check your mount points. If `ls /data/media` doesn't return anything then I assume something is wrong with the volume mount rather than the Jellyfin container.

**Comment by Didr** [comment]
> Here you can see that the jellyfin pod has access to this folder (the PV is a local-storage volume).
> ![image](https://user-images.githubusercontent.com/48793689/113886371-9ec82880-978e-11eb-882d-72b197414a93.png)
> 
> I created the videos folder here, since this should be the /data/media root. The pod created config, data, log, metadata, plugins, root, and transcodes
> 

Judging from the screenshot it seems like you've mounted jellyfin-pvc-config to /home/storage/jellyfin/media, and jellyfin-pvc-media to /home/storage/jellyfin/media/videos. Is that correct?

**Comment by fabianvf** [comment]
@davesargrad hmm the nested mounts could be causing an issue if that's the case, but I'd echo what @Didr said, try execing into the pod and seeing what you can see on the FS from inside the pod. Could be permissions issues or any number of things, just need more info. Here's the volumes and volume mounts that I'm using:

```
      volumes:
        - name: tv
          persistentVolumeClaim:
            claimName: series
        - name: media
          persistentVolumeClaim:
            claimName: movies
        - name: config
          persistentVolumeClaim:
            claimName: config-10gi
```
```
          volumeMounts:
            - mountPath: /mnt/tv
              name: tv
              readOnly: true
            - mountPath: /mnt/movies
              name: media
              readOnly: true
            - mountPath: /config
              name: config
```
